# Generated by Django 4.2.8 on 2024-02-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userthings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_things', to=settings.AUTH_USER_MODEL),
        ),
    ]
