# Generated by Django 4.2.8 on 2024-02-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_things_user'),
    ]

    operations = [
    ]
