# Generated by Django 4.2.8 on 2024-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20240215_1216_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_things',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.user_things'),
        ),
    ]
