# Generated by Django 4.2.8 on 2024-02-19 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_alter_user_things_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_things',
            name='friends',
            field=models.ManyToManyField(blank=True, default=None, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
