# Generated by Django 4.2.8 on 2024-03-25 16:21

from django.db import migrations

def populate_nicks(apps, schema_editor):
    UserThings = apps.get_model('users', 'user_things')
    for user_thing in UserThings.objects.all():
        user_thing.nick = user_thing.user.username
        user_thing.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_things_friends'),
    ]

    operations = [ migrations.RunPython(populate_nicks),
    ]
