# Generated by Django 4.2.8 on 2024-03-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240325_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_things',
            name='nick',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
