# Generated by Django 4.2.8 on 2024-04-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_things_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_things',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
