version: '3.8'

services:

  web:
    build: .
    container_name: django
    volumes:
      - ./:/app
      - ./static/:/app/static
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CACHE_HOST=${CACHE_HOST}
      - CACHE_PORT=${CACHE_PORT}
    depends_on:
      - my-postgres
      - redis

  my-postgres:
    image: postgres:15
    container_name: db
    environment:
     - POSTGRES_DB=${DATABASE_NAME}
     - POSTGRES_USER=${DATABASE_USER}
     - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - '443:443'
    depends_on:
      - web
    volumes:
      - ./static/:/app/static
      - ./media/:/app/media

volumes:
  pg_data:
